version: 2
updates:
  - package-ecosystem: npm
    directories: ["/", "/app"]
    schedule:
      interval: weekly
  - package-ecosystem: composer
    directory: /app
    schedule:
      interval: weekly
  - package-ecosystem: bundler
    directories: ["/", "/docs"]
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
