<?php

declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * Offices seed.
 */
class DevLoadOfficesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'name' => 'Crown',
                'department_id' => 1,
                'requires_warrant' => 0,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => NULL,
                'term_length' => 1,
                'modified' => '2025-01-02 20:08:58',
                'created' => '2025-01-02 14:17:56',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 2,
                'name' => 'Kingdom Earl Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:05:36',
                'created' => '2025-01-02 14:37:55',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 3,
                'name' => 'Kingdom Rapier Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 2,
                'term_length' => 2,
                'modified' => '2025-01-12 17:05:14',
                'created' => '2025-01-02 14:38:32',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 4,
                'name' => 'Regional Rapier Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:06:20',
                'created' => '2025-01-02 15:32:17',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 5,
                'name' => 'Local Rapier Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:04:27',
                'created' => '2025-01-02 15:32:44',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 4,
            ],
            [
                'id' => 6,
                'name' => 'Kingdom Chronicler',
                'department_id' => 9,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:17:35',
                'created' => '2025-01-02 15:43:54',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 7,
                'name' => 'Kingdom Chronicler Deputy',
                'department_id' => 9,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 6,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-02 15:44:26',
                'created' => '2025-01-02 15:44:26',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 6,
            ],
            [
                'id' => 8,
                'name' => 'Regional Chronicler',
                'department_id' => 9,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:04:38',
                'created' => '2025-01-02 15:45:03',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 6,
            ],
            [
                'id' => 9,
                'name' => 'Local Chronicler',
                'department_id' => 9,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-02 15:52:01',
                'created' => '2025-01-02 15:52:01',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 8,
            ],
            [
                'id' => 10,
                'name' => 'Kingdom MoAS',
                'department_id' => 5,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:23:37',
                'created' => '2025-01-02 16:01:49',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 11,
                'name' => 'Kingdom Earl Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 2,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-02 16:03:03',
                'created' => '2025-01-02 16:03:03',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 12,
                'name' => 'Kingdom MoAS Deputy',
                'department_id' => 5,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 10,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-02 16:03:41',
                'created' => '2025-01-02 16:03:41',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 10,
            ],
            [
                'id' => 13,
                'name' => 'Regional MoAS',
                'department_id' => 5,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:05:01',
                'created' => '2025-01-02 16:20:33',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 10,
            ],
            [
                'id' => 14,
                'name' => 'Local MoAS',
                'department_id' => 5,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-02 16:21:02',
                'created' => '2025-01-02 16:21:02',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 13,
            ],
            [
                'id' => 17,
                'name' => 'Kingdom Armored Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 2,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 18:33:08',
                'created' => '2025-01-06 01:20:16',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 16,
                'name' => 'Regional Armored Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 15:30:05',
                'created' => '2025-01-06 01:16:28',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Region"',
                'reports_to_id' => 17,
            ],
            [
                'id' => 15,
                'name' => 'Local Armored Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 01:51:01',
                'created' => '2025-01-06 01:12:23',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 16,
            ],
            [
                'id' => 18,
                'name' => 'Kingdom Webminister',
                'department_id' => 4,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:18:04',
                'created' => '2025-01-07 16:08:48',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 19,
                'name' => 'Deleted: Application Admin',
                'department_id' => 4,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 18,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 14:48:19',
                'created' => '2025-01-07 16:11:56',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => '2025-01-13 14:48:19',
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 18,
            ],
            [
                'id' => 20,
                'name' => 'Kingdom Webminister Deputy',
                'department_id' => 4,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 18,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 14:48:51',
                'created' => '2025-01-07 16:22:45',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 18,
            ],
            [
                'id' => 21,
                'name' => 'Local Webminister',
                'department_id' => 4,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-07 16:38:21',
                'created' => '2025-01-07 16:38:21',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 18,
            ],
            [
                'id' => 22,
                'name' => 'Kingdom Webminister - AMP Admin',
                'department_id' => 4,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 18,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 14:49:14',
                'created' => '2025-01-07 21:23:35',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 18,
            ],
            [
                'id' => 23,
                'name' => 'At Large: Rapier Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 3,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:17:04',
                'created' => '2025-01-12 17:07:25',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 24,
                'name' => 'Kingdom Missile Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 2,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:13:59',
                'created' => '2025-01-12 17:09:02',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 25,
                'name' => 'Kingdom C&T Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 3,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:13:38',
                'created' => '2025-01-12 17:10:26',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 26,
                'name' => 'At Large: C&T Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 25,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:16:51',
                'created' => '2025-01-12 17:14:22',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 25,
            ],
            [
                'id' => 28,
                'name' => 'Kingdom Seneschal',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:22:23',
                'created' => '2025-01-12 17:20:13',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 29,
                'name' => 'Kingdom Seneschal Deputy',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 28,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:20:52',
                'created' => '2025-01-12 17:20:52',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 28,
            ],
            [
                'id' => 30,
                'name' => 'Regional Seneschal',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:22:52',
                'created' => '2025-01-12 17:21:31',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 28,
            ],
            [
                'id' => 31,
                'name' => 'Local Seneschal',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:22:43',
                'created' => '2025-01-12 17:21:57',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 30,
            ],
            [
                'id' => 32,
                'name' => 'Kingdom Rapier Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:36:25',
                'created' => '2025-01-12 17:36:25',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 33,
                'name' => 'Kingdom Missile Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 24,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:36:59',
                'created' => '2025-01-12 17:36:59',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 24,
            ],
            [
                'id' => 34,
                'name' => 'At Large: Armored Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 17,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:16:22',
                'created' => '2025-01-12 17:38:20',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 17,
            ],
            [
                'id' => 35,
                'name' => 'Kingdom Equestrian Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 2,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 17:39:07',
                'created' => '2025-01-12 17:39:07',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 36,
                'name' => 'At Large: C&T 2 Handed Weapons Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 25,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:16:34',
                'created' => '2025-01-12 17:41:11',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 25,
            ],
            [
                'id' => 37,
                'name' => 'At Large: Equestrian Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 35,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-18 21:22:20',
                'created' => '2025-01-12 17:44:06',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 35,
            ],
            [
                'id' => 38,
                'name' => 'At Large: Wooden Lance Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 35,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-12 17:45:44',
                'created' => '2025-01-12 17:45:44',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 35,
            ],
            [
                'id' => 39,
                'name' => 'Kingdom Youth Rapier Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 3,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 17:18:16',
                'created' => '2025-01-12 18:05:03',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 40,
                'name' => 'Kingdom Youth Armored Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 17,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 18:05:53',
                'created' => '2025-01-12 18:05:53',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 17,
            ],
            [
                'id' => 41,
                'name' => 'Star Principal Herald',
                'department_id' => 10,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 18:07:11',
                'created' => '2025-01-12 18:07:11',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 42,
                'name' => 'Kingdom Herald Deputy',
                'department_id' => 10,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 41,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-15 01:10:30',
                'created' => '2025-01-12 18:08:35',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 41,
            ],
            [
                'id' => 43,
                'name' => 'Regional Herald',
                'department_id' => 10,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-12 18:09:37',
                'created' => '2025-01-12 18:09:37',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 41,
            ],
            [
                'id' => 44,
                'name' => 'Local Herald',
                'department_id' => 10,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 19:36:40',
                'created' => '2025-01-12 18:09:56',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 43,
            ],
            [
                'id' => 45,
                'name' => 'Kingdom Chatelaine',
                'department_id' => 7,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:40:12',
                'created' => '2025-01-12 21:55:13',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 46,
                'name' => 'Regional Chatelaine',
                'department_id' => 7,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:41:21',
                'created' => '2025-01-12 21:55:41',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 45,
            ],
            [
                'id' => 47,
                'name' => 'Local Chatelaine',
                'department_id' => 7,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:40:49',
                'created' => '2025-01-12 21:56:03',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 46,
            ],
            [
                'id' => 48,
                'name' => 'Kingdom Chatelaine Deputy',
                'department_id' => 7,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 45,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:40:28',
                'created' => '2025-01-12 21:56:30',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 45,
            ],
            [
                'id' => 49,
                'name' => 'Local Seneschal Deputy',
                'department_id' => 2,
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 31,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 14:21:26',
                'created' => '2025-01-13 14:21:26',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 31,
            ],
            [
                'id' => 50,
                'name' => 'Kingdom Social Media Officer',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 28,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 14:28:54',
                'created' => '2025-01-13 14:28:54',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 28,
            ],
            [
                'id' => 51,
                'name' => 'Kingdom Youth and Family Officer',
                'department_id' => 12,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:02:54',
                'created' => '2025-01-13 14:33:31',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 52,
                'name' => 'Regional Youth and Family Officer',
                'department_id' => 12,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:03:38',
                'created' => '2025-01-13 14:35:07',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 51,
            ],
            [
                'id' => 53,
                'name' => 'Local Youth and Family Officer',
                'department_id' => 12,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:03:21',
                'created' => '2025-01-13 14:35:31',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 52,
            ],
            [
                'id' => 54,
                'name' => 'Local Social Media Officer',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 1,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 19:50:45',
                'created' => '2025-01-13 14:36:05',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 50,
            ],
            [
                'id' => 55,
                'name' => 'Local Rapier Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 5,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 15:28:28',
                'created' => '2025-01-13 15:28:28',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 5,
            ],
            [
                'id' => 56,
                'name' => 'Local Armored Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 15,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 15:29:23',
                'created' => '2025-01-13 15:29:23',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 15,
            ],
            [
                'id' => 57,
                'name' => 'Local Heraldry Deputy',
                'department_id' => 10,
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 43,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 19:34:38',
                'created' => '2025-01-13 15:31:05',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 43,
            ],
            [
                'id' => 58,
                'name' => 'Kingdom Target Archery Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 24,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 17:08:04',
                'created' => '2025-01-13 17:06:57',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 24,
            ],
            [
                'id' => 59,
                'name' => 'Kingdom Thrown Weapons Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 24,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 17:07:41',
                'created' => '2025-01-13 17:07:41',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 24,
            ],
            [
                'id' => 60,
                'name' => 'Kingdom Siege Weapons Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 24,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 17:10:47',
                'created' => '2025-01-13 17:10:47',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 24,
            ],
            [
                'id' => 61,
                'name' => 'Kingdom Combat Archery Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 24,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 17:11:20',
                'created' => '2025-01-13 17:11:20',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 24,
            ],
            [
                'id' => 62,
                'name' => 'At Large: Target Archery Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 58,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:12:11',
                'created' => '2025-01-13 17:12:11',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 58,
            ],
            [
                'id' => 63,
                'name' => 'At Large: Combat Archery Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 61,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:13:30',
                'created' => '2025-01-13 17:13:30',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 61,
            ],
            [
                'id' => 64,
                'name' => 'At Large: Thrown Weapons Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 59,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:14:08',
                'created' => '2025-01-13 17:14:08',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 59,
            ],
            [
                'id' => 65,
                'name' => 'At Large: Siege Weapons Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 60,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:15:32',
                'created' => '2025-01-13 17:15:32',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 60,
            ],
            [
                'id' => 66,
                'name' => 'At Large: Youth Rapier Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 39,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:26:32',
                'created' => '2025-01-13 17:26:32',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 39,
            ],
            [
                'id' => 67,
                'name' => 'At Large: Youth Armored Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 40,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-13 17:27:18',
                'created' => '2025-01-13 17:27:18',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 40,
            ],
            [
                'id' => 68,
                'name' => 'Kingdom Armored Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 17,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 17:31:06',
                'created' => '2025-01-13 17:31:06',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 17,
            ],
            [
                'id' => 69,
                'name' => 'Regional Seneschal Deputy',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 30,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 19:19:09',
                'created' => '2025-01-13 19:19:09',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 30,
            ],
            [
                'id' => 70,
                'name' => 'Regional Webminister',
                'department_id' => 4,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:01:02',
                'created' => '2025-01-13 20:01:02',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality"',
                'reports_to_id' => 18,
            ],
            [
                'id' => 71,
                'name' => 'Regional Herald Deputy',
                'department_id' => 10,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 43,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:11:32',
                'created' => '2025-01-13 20:11:32',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 43,
            ],
            [
                'id' => 72,
                'name' => 'Local Chatelaine Deputy',
                'department_id' => 7,
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 47,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:41:08',
                'created' => '2025-01-13 20:34:40',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 47,
            ],
            [
                'id' => 73,
                'name' => 'Kingdom Treasurer',
                'department_id' => 6,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:37:59',
                'created' => '2025-01-13 20:37:38',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 74,
                'name' => 'Kingdom Treasurer Deputy',
                'department_id' => 6,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 73,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:39:20',
                'created' => '2025-01-13 20:38:42',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 73,
            ],
            [
                'id' => 75,
                'name' => 'Deleted: Regional Treasurer',
                'department_id' => 6,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => 73,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:46:18',
                'created' => '2025-01-13 20:40:26',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => '2025-01-13 20:46:18',
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 73,
            ],
            [
                'id' => 77,
                'name' => 'Regional Treasurer',
                'department_id' => 6,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 20:47:07',
                'created' => '2025-01-13 20:47:07',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 73,
            ],
            [
                'id' => 76,
                'name' => 'Local Treasurer',
                'department_id' => 6,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 21:03:50',
                'created' => '2025-01-13 20:41:04',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 77,
            ],
            [
                'id' => 78,
                'name' => 'Kingdom Social Media Deputy',
                'department_id' => 2,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 50,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 21:56:33',
                'created' => '2025-01-13 21:56:33',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 50,
            ],
            [
                'id' => 79,
                'name' => 'Regional Chronicler Deputy',
                'department_id' => 9,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 8,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-13 22:03:17',
                'created' => '2025-01-13 22:03:17',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 8,
            ],
            [
                'id' => 80,
                'name' => 'Kingdom Earl Marshal Deputy - Secretary ',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 2,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 19:27:30',
                'created' => '2025-01-14 19:27:30',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 81,
                'name' => 'Local Thrown Weapons Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 20:40:55',
                'created' => '2025-01-14 19:32:14',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 59,
            ],
            [
                'id' => 82,
                'name' => 'Regional Rapier Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 4,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 19:48:16',
                'created' => '2025-01-14 19:48:16',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 4,
            ],
            [
                'id' => 83,
                'name' => 'Local Target Archery Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 20:41:00',
                'created' => '2025-01-14 20:01:40',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 58,
            ],
            [
                'id' => 84,
                'name' => 'Principality Earl Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 20:08:25',
                'created' => '2025-01-14 20:08:25',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality"',
                'reports_to_id' => 2,
            ],
            [
                'id' => 85,
                'name' => 'Regional Target Archery Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-14 20:35:55',
                'created' => '2025-01-14 20:35:12',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_id' => 24,
            ],
            [
                'id' => 86,
                'name' => 'Coronet',
                'department_id' => 1,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => NULL,
                'grants_role_id' => NULL,
                'term_length' => 1,
                'modified' => '2025-01-15 02:28:09',
                'created' => '2025-01-15 02:28:09',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => NULL,
            ],
            [
                'id' => 87,
                'name' => 'Local Target Archery Marshal Deputy',
                'department_id' => 3,
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 83,
                'grants_role_id' => NULL,
                'term_length' => 2,
                'modified' => '2025-01-15 16:31:05',
                'created' => '2025-01-15 16:31:05',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_id' => 83,
            ],
            [
                'id' => 88,
                'name' => 'At Large: Rapier Spear Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 3,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-17 13:29:10',
                'created' => '2025-01-17 13:29:10',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 89,
                'name' => 'At Large: Rapier Reduced Armor Experiment Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 3,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-17 13:31:25',
                'created' => '2025-01-17 13:31:25',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 3,
            ],
            [
                'id' => 90,
                'name' => 'At Large: C&T - Historic Combat Experiment Authorizing Marshal',
                'department_id' => 3,
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_id' => 25,
                'grants_role_id' => NULL,
                'term_length' => 4,
                'modified' => '2025-01-17 17:03:02',
                'created' => '2025-01-17 17:00:59',
                'created_by' => 1,
                'modified_by' => 1,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_id' => 25,
            ],
        ];

        $table = $this->table('officers_offices');
        $table->insert($data)->save();
    }
}