<?php

declare(strict_types=1);

use Migrations\BaseSeed;

require_once __DIR__ . '/Lib/SeedHelpers.php';

/**
 * Offices seed.
 */
class DevLoadOfficesSeed extends BaseSeed
{
    /**
     * Get data for seeding.
     *
     * @return array
     */
    public function getData(): array
    {
        $adminId = SeedHelpers::getMemberId('admin@test.com');
        return [
            [
                // 'id' => 1,
                'name' => 'Crown',
                'department_id' => SeedHelpers::getDepartmentIdByName('Nobility'),
                'requires_warrant' => 0,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,

                'term_length' => 12,
                'modified' => '2025-01-02 20:08:58',
                'created' => '2025-01-02 14:17:56',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 2,
                'name' => 'Kingdom Earl Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,

                'term_length' => 24,
                'modified' => '2025-01-12 17:05:36',
                'created' => '2025-01-02 14:37:55',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 3,
                'name' => 'Kingdom Rapier Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Earl Marshal',
                'term_length' => 24,
                'modified' => '2025-01-12 17:05:14',
                'created' => '2025-01-02 14:38:32',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 4,
                'name' => 'Regional Rapier Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:06:20',
                'created' => '2025-01-02 15:32:17',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 5,
                'name' => 'Local Rapier Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:04:27',
                'created' => '2025-01-02 15:32:44',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Rapier Marshal',
            ],
            [
                // 'id' => 6,
                'name' => 'Kingdom Chronicler',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chronicler'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:17:35',
                'created' => '2025-01-02 15:43:54',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 7,
                'name' => 'Kingdom Chronicler Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chronicler'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Chronicler',

                'term_length' => 24,
                'modified' => '2025-01-02 15:44:26',
                'created' => '2025-01-02 15:44:26',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Chronicler',
            ],
            [
                // 'id' => 8,
                'name' => 'Regional Chronicler',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chronicler'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'term_length' => 24,
                'modified' => '2025-01-12 17:04:38',
                'created' => '2025-01-02 15:45:03',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Kingdom Chronicler',
            ],
            [
                // 'id' => 9,
                'name' => 'Local Chronicler',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chronicler'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-02 15:52:01',
                'created' => '2025-01-02 15:52:01',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Chronicler',
            ],
            [
                // 'id' => 10,
                'name' => 'Kingdom MoAS',
                'department_id' => SeedHelpers::getDepartmentIdByName('Arts & Sciences'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:23:37',
                'created' => '2025-01-02 16:01:49',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 11,
                'name' => 'Kingdom Earl Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Earl Marshal',

                'term_length' => 24,
                'modified' => '2025-01-02 16:03:03',
                'created' => '2025-01-02 16:03:03',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 12,
                'name' => 'Kingdom MoAS Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Arts & Sciences'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom MoAS',

                'term_length' => 24,
                'modified' => '2025-01-02 16:03:41',
                'created' => '2025-01-02 16:03:41',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom MoAS',
            ],
            [
                // 'id' => 13,
                'name' => 'Regional MoAS',
                'department_id' => SeedHelpers::getDepartmentIdByName('Arts & Sciences'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:05:01',
                'created' => '2025-01-02 16:20:33',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'deputy_to_name' => 'Kingdom MoAS',
            ],
            [
                // 'id' => 14,
                'name' => 'Local MoAS',
                'department_id' => SeedHelpers::getDepartmentIdByName('Arts & Sciences'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-02 16:21:02',
                'created' => '2025-01-02 16:21:02',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional MoAS',
            ],
            [
                // 'id' => 17,
                'name' => 'Kingdom Armored Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Earl Marshal',

                'term_length' => 24,
                'modified' => '2025-01-12 18:33:08',
                'created' => '2025-01-06 01:20:16',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 16,
                'name' => 'Regional Armored Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 15:30:05',
                'created' => '2025-01-06 01:16:28',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Region"',
                'reports_to_name' => 'Kingdom Armored Marshal',
            ],
            [
                // 'id' => 15,
                'name' => 'Local Armored Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-14 01:51:01',
                'created' => '2025-01-06 01:12:23',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Armored Marshal',
            ],
            [
                // 'id' => 18,
                'name' => 'Kingdom Webminister',
                'department_id' => SeedHelpers::getDepartmentIdByName('Webministry'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:18:04',
                'created' => '2025-01-07 16:08:48',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 19,
                'name' => 'Deleted: Application Admin',
                'department_id' => SeedHelpers::getDepartmentIdByName('Webministry'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Webminister',

                'term_length' => 24,
                'modified' => '2025-01-13 14:48:19',
                'created' => '2025-01-07 16:11:56',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => '2025-01-13 14:48:19',
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Webminister',
            ],
            [
                // 'id' => 20,
                'name' => 'Kingdom Webminister Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Webministry'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Webminister',

                'term_length' => 24,
                'modified' => '2025-01-13 14:48:51',
                'created' => '2025-01-07 16:22:45',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Webminister',
            ],
            [
                // 'id' => 21,
                'name' => 'Local Webminister',
                'department_id' => SeedHelpers::getDepartmentIdByName('Webministry'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-07 16:38:21',
                'created' => '2025-01-07 16:38:21',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'deputy_to_name' => 'Kingdom Webminister',
            ],
            [
                // 'id' => 22,
                'name' => 'Kingdom Webminister - AMP Admin',
                'department_id' => SeedHelpers::getDepartmentIdByName('Webministry'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Webminister',

                'term_length' => 24,
                'modified' => '2025-01-13 14:49:14',
                'created' => '2025-01-07 21:23:35',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Webminister',
            ],
            [
                // 'id' => 23,
                'name' => 'At Large: Rapier Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Rapier Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:17:04',
                'created' => '2025-01-12 17:07:25',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 24,
                'name' => 'Kingdom Missile Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Earl Marshal',

                'term_length' => 24,
                'modified' => '2025-01-12 17:13:59',
                'created' => '2025-01-12 17:09:02',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 25,
                'name' => 'Kingdom C&T Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Rapier Marshal',

                'term_length' => 24,
                'modified' => '2025-01-12 17:13:38',
                'created' => '2025-01-12 17:10:26',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 26,
                'name' => 'At Large: C&T Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom C&T Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:16:51',
                'created' => '2025-01-12 17:14:22',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom C&T Marshal',
            ],
            [
                // 'id' => 28,
                'name' => 'Kingdom Seneschal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:22:23',
                'created' => '2025-01-12 17:20:13',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 29,
                'name' => 'Kingdom Seneschal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Seneschal',

                'term_length' => 24,
                'modified' => '2025-01-12 17:20:52',
                'created' => '2025-01-12 17:20:52',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Seneschal',
            ],
            [
                // 'id' => 30,
                'name' => 'Regional Seneschal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:22:52',
                'created' => '2025-01-12 17:21:31',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Kingdom Seneschal',
            ],
            [
                // 'id' => 31,
                'name' => 'Local Seneschal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 17:22:43',
                'created' => '2025-01-12 17:21:57',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Seneschal',
            ],
            [
                // 'id' => 32,
                'name' => 'Kingdom Rapier Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,


                'term_length' => 24,
                'modified' => '2025-01-12 17:36:25',
                'created' => '2025-01-12 17:36:25',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 33,
                'name' => 'Kingdom Missile Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Missile Marshal',

                'term_length' => 24,
                'modified' => '2025-01-12 17:36:59',
                'created' => '2025-01-12 17:36:59',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Missile Marshal',
            ],
            [
                // 'id' => 34,
                'name' => 'At Large: Armored Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Armored Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:16:22',
                'created' => '2025-01-12 17:38:20',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Armored Marshal',
            ],
            [
                // 'id' => 35,
                'name' => 'Kingdom Equestrian Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Earl Marshal',

                'term_length' => 24,
                'modified' => '2025-01-12 17:39:07',
                'created' => '2025-01-12 17:39:07',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 36,
                'name' => 'At Large: C&T 2 Handed Weapons Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom C&T Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:16:34',
                'created' => '2025-01-12 17:41:11',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom C&T Marshal',
            ],
            [
                // 'id' => 37,
                'name' => 'At Large: Equestrian Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Equestrian Marshal',

                'term_length' => 48,
                'modified' => '2025-01-18 21:22:20',
                'created' => '2025-01-12 17:44:06',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Equestrian Marshal',
            ],
            [
                // 'id' => 38,
                'name' => 'At Large: Wooden Lance Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Equestrian Marshal',

                'term_length' => 48,
                'modified' => '2025-01-12 17:45:44',
                'created' => '2025-01-12 17:45:44',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Equestrian Marshal',
            ],
            [
                // 'id' => 39,
                'name' => 'Kingdom Youth Rapier Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Rapier Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 17:18:16',
                'created' => '2025-01-12 18:05:03',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 40,
                'name' => 'Kingdom Youth Armored Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Armored Marshal',

                'term_length' => 24,
                'modified' => '2025-01-12 18:05:53',
                'created' => '2025-01-12 18:05:53',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Armored Marshal',
            ],
            [
                // 'id' => 41,
                'name' => 'Star Principal Herald',
                'department_id' => SeedHelpers::getDepartmentIdByName('College of Heralds'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 18:07:11',
                'created' => '2025-01-12 18:07:11',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 42,
                'name' => 'Kingdom Herald Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('College of Heralds'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Star Principal Herald',

                'term_length' => 24,
                'modified' => '2025-01-15 01:10:30',
                'created' => '2025-01-12 18:08:35',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Star Principal Herald',
            ],
            [
                // 'id' => 43,
                'name' => 'Regional Herald',
                'department_id' => SeedHelpers::getDepartmentIdByName('College of Heralds'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-12 18:09:37',
                'created' => '2025-01-12 18:09:37',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'deputy_to_name' => 'Star Principal Herald',
            ],
            [
                // 'id' => 44,
                'name' => 'Local Herald',
                'department_id' => SeedHelpers::getDepartmentIdByName('College of Heralds'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 19:36:40',
                'created' => '2025-01-12 18:09:56',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Herald',
            ],
            [
                // 'id' => 45,
                'name' => 'Kingdom Chatelaine',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chatelaine'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:40:12',
                'created' => '2025-01-12 21:55:13',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 46,
                'name' => 'Regional Chatelaine',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chatelaine'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:41:21',
                'created' => '2025-01-12 21:55:41',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Kingdom Chatelaine',
            ],
            [
                // 'id' => 47,
                'name' => 'Local Chatelaine',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chatelaine'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:40:49',
                'created' => '2025-01-12 21:56:03',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Chatelaine',
            ],
            [
                // 'id' => 48,
                'name' => 'Kingdom Chatelaine Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chatelaine'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Chatelaine',

                'term_length' => 24,
                'modified' => '2025-01-13 20:40:28',
                'created' => '2025-01-12 21:56:30',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Chatelaine',
            ],
            [
                // 'id' => 49,
                'name' => 'Local Seneschal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Local Seneschal',

                'term_length' => 24,
                'modified' => '2025-01-13 14:21:26',
                'created' => '2025-01-13 14:21:26',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'deputy_to_name' => 'Local Seneschal',
            ],
            [
                // 'id' => 50,
                'name' => 'Kingdom Social Media Officer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Seneschal',

                'term_length' => 24,
                'modified' => '2025-01-13 14:28:54',
                'created' => '2025-01-13 14:28:54',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Seneschal',
            ],
            [
                // 'id' => 51,
                'name' => 'Kingdom Youth and Family Officer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Youth and Family Office'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:02:54',
                'created' => '2025-01-13 14:33:31',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 52,
                'name' => 'Regional Youth and Family Officer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Youth and Family Office'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:03:38',
                'created' => '2025-01-13 14:35:07',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Kingdom Youth and Family Officer',
            ],
            [
                // 'id' => 53,
                'name' => 'Local Youth and Family Officer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Youth and Family Office'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:03:21',
                'created' => '2025-01-13 14:35:31',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Youth and Family Officer',
            ],
            [
                // 'id' => 54,
                'name' => 'Local Social Media Officer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 1,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 19:50:45',
                'created' => '2025-01-13 14:36:05',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'deputy_to_name' => 'Kingdom Social Media Officer',
            ],
            [
                // 'id' => 55,
                'name' => 'Local Rapier Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Local Rapier Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 15:28:28',
                'created' => '2025-01-13 15:28:28',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Local Rapier Marshal',
            ],
            [
                // 'id' => 56,
                'name' => 'Local Armored Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Local Armored Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 15:29:23',
                'created' => '2025-01-13 15:29:23',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'deputy_to_name' => 'Local Armored Marshal',
            ],
            [
                // 'id' => 57,
                'name' => 'Local Heraldry Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('College of Heralds'),
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Regional Herald',

                'term_length' => 24,
                'modified' => '2025-01-13 19:34:38',
                'created' => '2025-01-13 15:31:05',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Regional Herald',
            ],
            [
                // 'id' => 58,
                'name' => 'Kingdom Target Archery Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Missile Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 17:08:04',
                'created' => '2025-01-13 17:06:57',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Missile Marshal',
            ],
            [
                // 'id' => 59,
                'name' => 'Kingdom Thrown Weapons Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Missile Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 17:07:41',
                'created' => '2025-01-13 17:07:41',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Missile Marshal',
            ],
            [
                // 'id' => 60,
                'name' => 'Kingdom Siege Weapons Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Missile Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 17:10:47',
                'created' => '2025-01-13 17:10:47',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Missile Marshal',
            ],
            [
                // 'id' => 61,
                'name' => 'Kingdom Combat Archery Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Missile Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 17:11:20',
                'created' => '2025-01-13 17:11:20',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Missile Marshal',
            ],
            [
                // 'id' => 62,
                'name' => 'At Large: Target Archery Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Target Archery Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:12:11',
                'created' => '2025-01-13 17:12:11',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Target Archery Marshal',
            ],
            [
                // 'id' => 63,
                'name' => 'At Large: Combat Archery Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Combat Archery Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:13:30',
                'created' => '2025-01-13 17:13:30',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Combat Archery Marshal',
            ],
            [
                // 'id' => 64,
                'name' => 'At Large: Thrown Weapons Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Thrown Weapons Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:14:08',
                'created' => '2025-01-13 17:14:08',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Thrown Weapons Marshal',
            ],
            [
                // 'id' => 65,
                'name' => 'At Large: Siege Weapons Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Siege Weapons Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:15:32',
                'created' => '2025-01-13 17:15:32',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Siege Weapons Marshal',
            ],
            [
                // 'id' => 66,
                'name' => 'At Large: Youth Rapier Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Youth Rapier Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:26:32',
                'created' => '2025-01-13 17:26:32',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Youth Rapier Marshal',
            ],
            [
                // 'id' => 67,
                'name' => 'At Large: Youth Armored Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Youth Armored Marshal',

                'term_length' => 48,
                'modified' => '2025-01-13 17:27:18',
                'created' => '2025-01-13 17:27:18',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Youth Armored Marshal',
            ],
            [
                // 'id' => 68,
                'name' => 'Kingdom Armored Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Armored Marshal',

                'term_length' => 24,
                'modified' => '2025-01-13 17:31:06',
                'created' => '2025-01-13 17:31:06',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Armored Marshal',
            ],
            [
                // 'id' => 69,
                'name' => 'Regional Seneschal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Regional Seneschal',

                'term_length' => 24,
                'modified' => '2025-01-13 19:19:09',
                'created' => '2025-01-13 19:19:09',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Regional Seneschal',
            ],
            [
                // 'id' => 70,
                'name' => 'Regional Webminister',
                'department_id' => SeedHelpers::getDepartmentIdByName('Webministry'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:01:02',
                'created' => '2025-01-13 20:01:02',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality"',
                'deputy_to_name' => 'Kingdom Webminister',
            ],
            [
                // 'id' => 71,
                'name' => 'Regional Herald Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('College of Heralds'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Regional Herald',

                'term_length' => 24,
                'modified' => '2025-01-13 20:11:32',
                'created' => '2025-01-13 20:11:32',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Regional Herald',
            ],
            [
                // 'id' => 72,
                'name' => 'Local Chatelaine Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chatelaine'),
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Local Chatelaine',

                'term_length' => 24,
                'modified' => '2025-01-13 20:41:08',
                'created' => '2025-01-13 20:34:40',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'deputy_to_name' => 'Local Chatelaine',
            ],
            [
                // 'id' => 73,
                'name' => 'Kingdom Treasurer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Treasury'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:37:59',
                'created' => '2025-01-13 20:37:38',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 74,
                'name' => 'Kingdom Treasurer Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Treasury'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Treasurer',

                'term_length' => 24,
                'modified' => '2025-01-13 20:39:20',
                'created' => '2025-01-13 20:38:42',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Treasurer',
            ],
            [
                // 'id' => 75,
                'name' => 'Deleted: Regional Treasurer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Treasury'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,
                'deputy_to_name' => 'Kingdom Treasurer',

                'term_length' => 24,
                'modified' => '2025-01-13 20:46:18',
                'created' => '2025-01-13 20:40:26',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => '2025-01-13 20:46:18',
                'applicable_branch_types' => '"Principality","Region"',
                'deputy_to_name' => 'Kingdom Treasurer',
            ],
            [
                // 'id' => 77,
                'name' => 'Regional Treasurer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Treasury'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 20:47:07',
                'created' => '2025-01-13 20:47:07',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'deputy_to_name' => 'Kingdom Treasurer',
            ],
            [
                // 'id' => 76,
                'name' => 'Local Treasurer',
                'department_id' => SeedHelpers::getDepartmentIdByName('Treasury'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-13 21:03:50',
                'created' => '2025-01-13 20:41:04',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'deputy_to_name' => 'Regional Treasurer',
            ],
            [
                // 'id' => 78,
                'name' => 'Kingdom Social Media Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Seneschallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Social Media Officer',

                'term_length' => 24,
                'modified' => '2025-01-13 21:56:33',
                'created' => '2025-01-13 21:56:33',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'deputy_to_name' => 'Kingdom Social Media Officer',
            ],
            [
                // 'id' => 79,
                'name' => 'Regional Chronicler Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Chronicler'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Regional Chronicler',

                'term_length' => 24,
                'modified' => '2025-01-13 22:03:17',
                'created' => '2025-01-13 22:03:17',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Regional Chronicler',
            ],
            [
                // 'id' => 80,
                'name' => 'Kingdom Earl Marshal Deputy - Secretary ',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Earl Marshal',

                'term_length' => 24,
                'modified' => '2025-01-14 19:27:30',
                'created' => '2025-01-14 19:27:30',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 81,
                'name' => 'Local Thrown Weapons Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-14 20:40:55',
                'created' => '2025-01-14 19:32:14',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Kingdom Thrown Weapons Marshal',
            ],
            [
                // 'id' => 82,
                'name' => 'Regional Rapier Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Regional Rapier Marshal',

                'term_length' => 24,
                'modified' => '2025-01-14 19:48:16',
                'created' => '2025-01-14 19:48:16',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Regional Rapier Marshal',
            ],
            [
                // 'id' => 83,
                'name' => 'Local Target Archery Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-14 20:41:00',
                'created' => '2025-01-14 20:01:40',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Kingdom Target Archery Marshal',
            ],
            [
                // 'id' => 84,
                'name' => 'Principality Earl Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 1,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-14 20:08:25',
                'created' => '2025-01-14 20:08:25',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality"',
                'reports_to_name' => 'Kingdom Earl Marshal',
            ],
            [
                // 'id' => 85,
                'name' => 'Regional Target Archery Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 1,


                'term_length' => 24,
                'modified' => '2025-01-14 20:35:55',
                'created' => '2025-01-14 20:35:12',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Principality","Region"',
                'reports_to_name' => 'Kingdom Missile Marshal',
            ],
            [
                // 'id' => 86,
                'name' => 'Coronet',
                'department_id' => SeedHelpers::getDepartmentIdByName('Nobility'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,


                'term_length' => 12,
                'modified' => '2025-01-15 02:28:09',
                'created' => '2025-01-15 02:28:09',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',

            ],
            [
                // 'id' => 87,
                'name' => 'Local Target Archery Marshal Deputy',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 0,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Local Target Archery Marshal',

                'term_length' => 24,
                'modified' => '2025-01-15 16:31:05',
                'created' => '2025-01-15 16:31:05',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Local Group"',
                'reports_to_name' => 'Local Target Archery Marshal',
            ],
            [
                // 'id' => 88,
                'name' => 'At Large: Rapier Spear Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Rapier Marshal',

                'term_length' => 48,
                'modified' => '2025-01-17 13:29:10',
                'created' => '2025-01-17 13:29:10',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 89,
                'name' => 'At Large: Rapier Reduced Armor Experiment Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom Rapier Marshal',

                'term_length' => 48,
                'modified' => '2025-01-17 13:31:25',
                'created' => '2025-01-17 13:31:25',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom Rapier Marshal',
            ],
            [
                // 'id' => 90,
                'name' => 'At Large: C&T - Historic Combat Experiment Authorizing Marshal',
                'department_id' => SeedHelpers::getDepartmentIdByName('Marshallate'),
                'requires_warrant' => 1,
                'required_office' => 0,
                'can_skip_report' => 0,
                'only_one_per_branch' => 0,
                'deputy_to_name' => 'Kingdom C&T Marshal',

                'term_length' => 48,
                'modified' => '2025-01-17 17:03:02',
                'created' => '2025-01-17 17:00:59',
                'created_by' => $adminId,
                'modified_by' => $adminId,
                'deleted' => NULL,
                'applicable_branch_types' => '"Kingdom"',
                'reports_to_name' => 'Kingdom C&T Marshal',
            ],
        ];
    }

    public function run(): void
    {
        $data = $this->getData();
        $table = $this->table('officers_offices');
        //$options = $table->getAdapter()->getOptions();
        //$options['identity_insert'] = true;
        //$table->getAdapter()->setOptions($options);
        // offices that aren't deputies or report to anyone
        $topOfficers = array_filter($data, function ($office) {
            return !isset($office['deputy_to_name']) && !isset($office['reports_to_name']);
        });
        $table->insert($topOfficers)->save();
        $createdOffices = $topOfficers;
        // find all of the officers who are deputies or report to one of the officers in $createdOffices
        while (count($createdOffices) < count($data)) {
            //filter out the officers that have already been processed
            $officesToProcess = array_filter($data, function ($office) use ($createdOffices) {
                $createdNames = array_column($createdOffices, 'name');
                return !in_array($office['name'], $createdNames, true);
            });
            // find all of the officers who are deputies or report to one of the officers in $createdOffices
            $remainingOffices = array_filter($officesToProcess, function ($office) use ($createdOffices) {
                $createdNames = array_column($createdOffices, 'name');
                return (
                    (isset($office['deputy_to_name']) && in_array($office['deputy_to_name'], $createdNames, true)) ||
                    (isset($office['reports_to_name']) && in_array($office['reports_to_name'], $createdNames, true))
                );
            });
            if (empty($remainingOffices)) {
                break;
            }
            foreach ($remainingOffices as $office) {
                if (isset($office['deputy_to_name'])) {
                    $office['deputy_to_id'] = SeedHelpers::getOfficeIdByName($office['deputy_to_name']);
                }
                if (isset($office['reports_to_name'])) {
                    $office['reports_to_id'] = SeedHelpers::getOfficeIdByName($office['reports_to_name']);
                }
                unset($office['deputy_to_name'], $office['reports_to_name']);
                $table->insert($office)->save();
                $createdOffices[] = $office;
            }
        }
    }
}