remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

mermaid: true

# Additional configuration
include:
  - README.md
  - LICENSE.md

aux_links:
  "KMP on GitHub":
    - "https://github.com/Ansteorra/KMP"