source 'https://rubygems.org'

gem "jekyll"

gem 'webrick'  # Required for Ruby >= 3.0
gem 'kramdown-parser-gfm'
group :jekyll_plugins do
    gem "jekyll-relative-links"
    gem 'jekyll-remote-theme'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
  end

