source 'https://rubygems.org'

gem "jekyll"
group :jekyll_plugins do
    gem "jekyll-remote-theme"
    gem "jekyll-relative-links"
    gem 'jekyll-mermaid'
  end
gem 'webrick'  # Required for Ruby >= 3.0
