name: SSH Command Execution

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Execute SSH Command
      uses: D3rHase/ssh-command-action@v0.2.2
      with:
        host: apps.ansteorra.org
        port: 22
        user: vscribe
        private_key: ${{ secrets.SSHKEY }}
        command: echo 'Hello, World!'
